# Generated by Django 6.0.3 on 2026-09-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_style', models.CharField(choices=[('hierarchical', 'Hierarchical'), ('non_hierarchical', 'Non Hierarchical'), ('relationship_anarchy', 'Relationship Anarchy'), ('parallel', 'Parallel'), ('other', 'Other')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
