# Generated by Django 6.0.3 on 2026-09-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0003_alter_partnership_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnership',
            name='special_dates',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
