# Generated by Django 6.0.3 on 2026-09-21 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0004_partnership_special_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnership',
            name='special_dates',
        ),
        migrations.AddField(
            model_name='partnership',
            name='anniversary',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SpecialDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partnership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_dates', to='relationship_app.partnership')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
