export const colors = {
  background: '#fff',
  cardBg: '#f5f5f5',
  soulmateAccent: '#7c4dff',
  soulmateBg: '#f0e6ff',
  primary: '#000',
  googleBlue: '#4285F4',
  secondary: '#e0e0e0',
  border: '#ccc',
  borderLight: '#ddd',
  borderMedium: '#e0e0e0',
  textPrimary: '#333',
  textSecondary: '#666',
  textMuted: '#999',
  error: '#F44336',
  success: '#4CAF50',
  neutral: '#9E9E9E',
  white: '#fff',
};
