# Generated by Django 6.0.3 on 2026-09-04 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gamification_app', '0001_initial'),
        ('relationship_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stardust',
            name='partnership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stardust', to='relationship_app.partnership'),
        ),
    ]
