# Generated by Django 6.0.3 on 2026-09-04 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gamification_app', '0002_initial'),
        ('relationship_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stardust',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stardust', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='streak',
            name='partnership',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to='relationship_app.partnership'),
        ),
        migrations.AddField(
            model_name='streakactivity',
            name='streak',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='gamification_app.streak'),
        ),
        migrations.AddField(
            model_name='streakactivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='stardust',
            unique_together={('partnership', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='streakactivity',
            unique_together={('streak', 'user')},
        ),
    ]
